blank_issues_enabled: false
contact_links:
  - name: MLFlow-Assist Community Support
    url: https://github.com/happyvibess/mlflow-assist/discussions
    about: Please ask and answer questions here.
  - name: Buy me a coffee
    url: https://www.buymeacoffee.com/happyvibess
    about: Support the project by buying me a coffee!

